### PR TITLE
update groveller files for osx

### PR DESCRIPTION
**Pull request by GOFAI**
I've tweaked the groveller files so they will look for the OpenCL headers in the right place under OSX. They work correctly on my MacBook.

### CODE REVIEW

**Comment by guicho271828** [comment]
Thanks for pointing it out! Would you also help me set up the OSX  build environment in .travis.yml ?

**Comment by GOFAI** [comment]
I'm afraid I'm unfamiliar with Travis, and in any case it may be premature--I had to modify the test suite because a few calls such as `(get-mem-object-info * :mem-associated-memobject)` cause sbcl to crash. (Past experience with `cl-opencl-3b` suggests that these result from quirks in Apple's provided OpenCL implementation.) After that, only the tests that ran on the CPU came out 100% correctly, but maybe they'll work fine on GPUs on other versions of OS X--under 10.9 my `cl-opencl-3b` demo worked correctly on the GPU, but after the upgrade to 10.10 it only worked on the CPU. 

For reference, this is what happens on the GPU tests:

``` CL
OpenCL Error:   :OUT-OF-RESOURCES for
OpenCL Error:   (EAZY-OPENCL.BINDINGS:ENQUEUE-READ-BUFFER CQ OUT-DEVICE
OpenCL Error:                                             EAZY-OPENCL.GROVEL:TRUE
OpenCL Error:                                             0 SIZE OUT-HOST 0
OpenCL Error:                                             (NULL-POINTER)
OpenCL Error:                                             (NULL-POINTER))
OpenCL Error:   (args:
OpenCL Error:   #S(EAZY-OPENCL.BINDINGS:BOXED-COMMAND-QUEUE :VALUE 3485392)
OpenCL Error:   #S(EAZY-OPENCL.BINDINGS:BOXED-BUFFER :VALUE 3608512) 1 0 13
OpenCL Error:   #.(SB-SYS:INT-SAP #X0CC6DFE8) 0 #.(SB-SYS:INT-SAP #X00000000)
OpenCL Error:   #.(SB-SYS:INT-SAP #X00000000) )
"Hello, W" f
```

**Comment by GOFAI** [comment]
Interestingly, increasing `size` from 13 to 32 or 64 still results in an `:OUT-OF-RESOURCES` error on the GPU, but the test actually passes nonetheless: 

``` CL
OpenCL Error:   :OUT-OF-RESOURCES for
OpenCL Error:   (EAZY-OPENCL.BINDINGS:ENQUEUE-READ-BUFFER CQ OUT-DEVICE
OpenCL Error:                                             EAZY-OPENCL.GROVEL:TRUE
OpenCL Error:                                             0 SIZE OUT-HOST 0
OpenCL Error:                                             (NULL-POINTER)
OpenCL Error:                                             (NULL-POINTER))
OpenCL Error:   (args:
OpenCL Error:   #S(EAZY-OPENCL.BINDINGS:BOXED-COMMAND-QUEUE :VALUE 4202032)
OpenCL Error:   #S(EAZY-OPENCL.BINDINGS:BOXED-BUFFER :VALUE 4320400) 1 0 64
OpenCL Error:   #.(SB-SYS:INT-SAP #X0CC6DFB8) 0 #.(SB-SYS:INT-SAP #X00000000)
OpenCL Error:   #.(SB-SYS:INT-SAP #X00000000) )
"Hello, World" .
```

**Comment by GOFAI** [comment]
I've adjusted the tests so that they pass on my machine with the exception of those using `:device-type-all`:
https://github.com/GOFAI/eazy-opencl/blob/master/t/package.lisp

**Comment by GOFAI** [comment]
Also, the tests, including those using `:device-type-all`, pass in ccl using a `size` of 13.

**Comment by guicho271828** [comment]
nice, added #31 to TODO.
would you add comments "OSX fails when ZZZZZ so I made it 32" ? I will merge this then.
I am inactive untill the deadline of a conference paper, so I can't investigate why 32 works atm.

**Comment by GOFAI** [comment]
Since it turns out the tests pass on CCL I think changing `size` from 13 to 32 is inappropriate--the problem obviously isn't with Apple's provided OpenCL platform after all, and I'm unsure what the problem is on SBCL. Instead, I've made the minimum changes needed to prevent crashes on OSX with both CCL and SBCL, while ensuring that all the tests run on other platforms.

**Comment by guicho271828** [comment]
Finally had the time to work on this. sorry for the delay!
I tried to make it work on travis, but without actual running OSX at hand it is hard to make pocl compile  on CI services. So I will merge this anyway.

**Pull request merged**
